<?php $this->headTitle('Home'); ?>
<?php if (!empty($this->error)): ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error:</strong> <?= $this->error ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif; ?>

<div class="row" style="padding-bottom: 10px">
    <div class="col">
        <h2>A Multipurpose Discord Bot</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-3 mb-3">
        <?php if ($this->isLoggedIn): ?>
            <div class="message">
                <div class="message-header">Manage Server</div>
                <div class="message-body">
                    <p>Selected Bot Instance:</p>
                    <p><?php
                        /** @var \App\TheDialgaTeam\Discord\Table\DiscordAppTable $selectedBotInstance */
                        $selectedBotInstance = $this->selectedBotInstance;
                        echo $selectedBotInstance->getAppName();
                        ?></p>
                    <div class="input-group mb-3">
                        <?php
                        /** @var \App\Form\GuildSelectionForm $guildSelectionForm */
                        $guildSelectionForm = $this->guildSelectionForm;
                        $guildSelectionForm->prepare();

                        echo $this->formRow($guildSelectionForm->get('guildId'));
                        ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="col-sm">
        <div class="message">
            <div class="message-header">Getting Started</div>
            <div class="message-body">
                <p>To get started, select the bot instance to login with discord and choose the guild you would like
                    to setup.</p>
                <?php
                /** @var \Zend\Form\Form $botSelectionForm */
                $botSelectionForm = $this->botSelectionForm;
                $botSelectionForm->setAttributes([
                    'action' => $this->url('discordAppAuthentication'),
                    'method' => 'post'
                ]);
                $botSelectionForm->prepare();

                echo $this->form()->openTag($botSelectionForm);
                ?>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="clientId">Bot Name</label>
                    </div>
                    <?= $this->formRow($botSelectionForm->get('clientId')) ?>
                </div>
                <?= $this->formRow($botSelectionForm->get('login')) ?>
                <?= $this->formRow($botSelectionForm->get('action')) ?>
                <?= $this->formRow($botSelectionForm->get('csrf')) ?>
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
        <div class="message">
            <div class="message-header">Features</div>
            <div class="message-body">
                <p>Free Game Notification - It will notify users about any potential free game that you can grab before
                    the promotion expires. (Offers are usually from humble bundle, gog or directly from steam)</p>
                <p>Custom Vanity Links - Provides a custom vanity link that user can join your server with. (Anti
                    Raiding + Custom Rate Limiting)</p>
            </div>
        </div>
    </div>
</div>