<?php
$this->headTitle('Home');

/** @var App\TheDialgaTeam\Discord\Table\DiscordAppTable $selectedBotInstance */
$selectedBotInstance = $this->selectedBotInstance;

/** @var App\Form\GuildSelectionForm $guildSelectionForm */
$guildSelectionForm = $this->guildSelectionForm;

if (isset($guildSelectionForm)) {
    $guildSelectionForm->setAttributes([
        'action' => $this->url('discordAppAuthentication'),
        'method' => 'post'
    ]);

    $guildSelectionForm->prepare();
}

/** @var App\Form\Home\BotSelectionForm $botSelectionForm */
$botSelectionForm = $this->botSelectionForm;

if (isset($botSelectionForm)) {
    $botSelectionForm->setAttributes([
        'action' => $this->url('discordAppAuthentication'),
        'method' => 'post'
    ]);

    $botSelectionForm->prepare();
}
?>

<?php if (!empty($this->error)): ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error:</strong> <?= $this->error ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif; ?>

<div class="row" style="padding-bottom: 10px">
    <div class="col">
        <h2>A Multipurpose Discord Bot</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-3 mb-3">
        <?php if ($this->isLoggedIn): ?>
            <div class="message">
                <div class="message-header">Manage Server</div>
                <div class="message-body">
                    <p>Selected Bot Instance:</p>
                    <p><?= isset($selectedBotInstance) ? $selectedBotInstance->getAppName() : '' ?></p>
                    <?= isset($guildSelectionForm) ? $this->form()->openTag($botSelectionForm) : '' ?>
                    <div class="input-group mb-3">
                        <?= isset($guildSelectionForm) ? $this->formRow($guildSelectionForm->get('guildId')) : '' ?>
                    </div>
                    <?= isset($guildSelectionForm) ? $this->formRow($guildSelectionForm->get('action')) : '' ?>
                    <?= isset($guildSelectionForm) ? $this->formRow($guildSelectionForm->get('csrf_guild_selection_form')) : '' ?>
                    <?= isset($guildSelectionForm) ? $this->form()->closeTag() : '' ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="col-sm">
        <div class="message">
            <div class="message-header">Getting Started</div>
            <div class="message-body">
                <p>To get started, select the bot instance to login with discord and choose the guild you would like
                    to setup.</p>
                <?= $this->form()->openTag($botSelectionForm) ?>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="clientId">Bot Name</label>
                    </div>
                    <?= $this->formRow($botSelectionForm->get('clientId')) ?>
                </div>
                <?= $this->formRow($botSelectionForm->get('login')) ?>
                <?= $this->formRow($botSelectionForm->get('action')) ?>
                <?= $this->formRow($botSelectionForm->get('csrf_bot_selection_form')) ?>
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
        <div class="message">
            <div class="message-header">Features</div>
            <div class="message-body">
                <p>Free Game Notification - It will notify users about any potential free game that you can grab before
                    the promotion expires. (Offers are usually from Humble Bundle, GoG or directly from Steam)</p>
                <p>Custom Vanity Links - Provides a custom vanity link that user can join your server with. (Anti
                    Raiding + Custom Rate Limiting)</p>
            </div>
        </div>
    </div>
</div>